services:
  - type: web
    name: replit-clone-web
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
  
  - type: worker
    name: replit-clone-worker
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node worker.js"
    envVars:
      - key: NODE_ENV
        value: production